### ISSUE TITLE
mp_plot_abundance geom flowbar modifying width

### ISSUE THREAD

**Issue by remi-leguern** [YuLab-SMU/MicrobiotaProcess#41]
I have an issue with the function mp_plot_abundance if I want to modify the width of the flowbar. 
If I try to change the width of geom_stratum from 1/3 to 1/2, the lines are not well connected.

```
mpse %>%
  mp_plot_abundance(
    .abundance=RareAbundance, 
    .group=Group3,
    taxa.class = Family,
    topn = 10,
    plot.group = TRUE,
    width = 1/2
  )
```

![CleanShot 2022-02-01 at 08 06 53](https://user-images.githubusercontent.com/56860387/151926153-2a5ccc47-c137-4e13-8dca-191dcca5d25e.png)

Did I miss something?

Thank you very much for your package, it is very helpful.

**Comment by xiangpin** [comment]
I'm very glad this package is useful to you. This issue was fixed by the github version. You can reinstall it via `remotes::install_github("YuLab-SMU/MicrobiotaProcess")`. 

```
library(MicrobiotaProcess)

data(mouse.time.mpse)

mouse.time.mpse %<>% mp_rrarefy()

mouse.time.mpse

p <- mouse.time.mpse %>%
     mp_plot_abundance(
       .abundance = RareAbundance,
       .group = time,
       plot.group = TRUE,
       width = 4/5         
     )
p
```
<img width="485" alt="屏幕快照 2022-02-01 19 27 33" src="https://user-images.githubusercontent.com/17870644/151961170-a66e741d-0c58-4705-8f8c-462085442ce0.png">

**Comment by remi-leguern** [comment]
Thank you very much, it works perfectly.
