### ISSUE TITLE
Abundance visualization for specific taxa

### ISSUE THREAD

**Issue by alienzj** [YuLab-SMU/MicrobiotaProcess#42]
@xiangpin

Hi,  Shuangbin, can we use  `mp_plot_abundance` to visualize specific taxa abundance ?

Expecially when we process amplicon data, if we want to display top ten genus, but we often got some unclassified taxa name, so how to display classified taxa name and exclude unclassified taxa name in abundance plot ?

I think if we extract abundance profile, then exclude unclassified taxa, and calculate `Others` abundance again, maybe we can generate the plot. If `mp_plot_abundance` support to visualize specific taxa abundance, that's great !

**Comment by xiangpin** [comment]
+ **how to display classified taxa name and exclude unclassified taxa name in abundance plot ?**
The github version has supported it. The unclassified taxa can be masked by setting the `rmun=TRUE` in `mp_plot_abundance`, then they will be considered as `Others`.

```
> library(MicrobiotaProcess)
> library(ggplot2)
> mpse <- readRDS("./demo_mpse.rds")
> mpse
# A MPSE-tibble (MPSE object) abstraction: 26,180 × 19
# OTU=770 | Samples=34 | Assays=Abundance | Taxonomy=Kingdom, Phylum, Class, Order, Family, Genus, Speies
   OTU     Sample Abundance barcode.sequence body.site  year month   day subject
   <chr>   <chr>      <dbl> <chr>            <chr>     <int> <int> <int> <chr>
 1 4b5eeb… L1S105      2183 AGTGCGATGCGT     gut        2009     3    17 subjec…
 2 fe30ff… L1S105         5 AGTGCGATGCGT     gut        2009     3    17 subjec…
 3 d29fe3… L1S105         0 AGTGCGATGCGT     gut        2009     3    17 subjec…
 4 868528… L1S105         0 AGTGCGATGCGT     gut        2009     3    17 subjec…
 5 154709… L1S105       802 AGTGCGATGCGT     gut        2009     3    17 subjec…
 6 1d2e5f… L1S105         0 AGTGCGATGCGT     gut        2009     3    17 subjec…
 7 0305a4… L1S105      1197 AGTGCGATGCGT     gut        2009     3    17 subjec…
 8 cb2fe0… L1S105         0 AGTGCGATGCGT     gut        2009     3    17 subjec…
 9 997056… L1S105         0 AGTGCGATGCGT     gut        2009     3    17 subjec…
10 3c9c43… L1S105         0 AGTGCGATGCGT     gut        2009     3    17 subjec…
# … with 26,170 more rows, and 10 more variables:
#   reported.antibiotic.usage <chr>, days.since.experiment.start <int>,
#   Confidence <dbl>, Kingdom <chr>, Phylum <chr>, Class <chr>, Order <chr>,
#   Family <chr>, Genus <chr>, Speies <chr>
> mpse %>% mp_plot_abundance(.abundance=Abundance, .group=c(subject, body.site), taxa.class=Genus, topn=20, force=T)
```
![xx](https://user-images.githubusercontent.com/17870644/154471525-5cfecf95-0e47-4838-8b7d-05afc10e9299.PNG)
```
mpse %>% mp_plot_abundance(.abundance=Abundance, .group=c(subject, body.site), taxa.class=Genus, topn=20, force=T, rmun=T)
```
![xx1](https://user-images.githubusercontent.com/17870644/154471802-248878da-5fda-4164-adc9-a3e14b4e592f.PNG)

```
mpse %>% mp_plot_abundance(.abundance=Abundance, .group=c(subject, body.site), taxa.class=Genus, topn=20, force=T, rmun=T, plot.group=T, width=3/4)
```
![xx2](https://user-images.githubusercontent.com/17870644/154472021-f3602c47-106c-4c2b-80b6-0e55661a7358.PNG)

You also can use `bar` or `heatmap` by setting `geom` parameter, referring to the manual of `mp_plot_abundance`.

+ **can we use mp_plot_abundance to visualize specific taxa abundance ?**
Now, the `mp_plot_abundance` does not support it, but this is easy because you can use `mp_extract_abundance` to extract taxa abundance and it can be visualized using `ggplot2` easily.

```
> mpse %>% mp_cal_abundance(.abundance=Abundance, force=T) %>% mp_extract_abundance(taxa.class="Genus", topn="all", rmun=T)
# A tibble: 198 × 3
   label              nodeClass AbundanceBySample
   <fct>              <chr>     <list>
 1 g__Deinococcus     Genus     <tibble [34 × 7]>
 2 g__Truepera        Genus     <tibble [34 × 7]>
 3 g__Actinomyces     Genus     <tibble [34 × 7]>
 4 g__Arcanobacterium Genus     <tibble [34 × 7]>
 5 g__Varibaculum     Genus     <tibble [34 × 7]>
 6 g__Brevibacterium  Genus     <tibble [34 × 7]>
 7 g__Corynebacterium Genus     <tibble [34 × 7]>
 8 g__Dermabacter     Genus     <tibble [34 × 7]>
 9 g__Blastococcus    Genus     <tibble [34 × 7]>
10 g__Kineococcus     Genus     <tibble [34 × 7]>
# … with 188 more rows
```
Then you can use `filter` to select the interesting taxa to display via `ggplot2`.

```
mpse %>% mp_cal_abundance(.abundance=Abundance, force=T) %>% mp_extract_abundance(taxa.class="Genus", topn="all", rmun=T) %>% dplyr::filter(label %in% c("g__Streptococcus", "g__Faecalibacterium")) %>% tidyr::unnest(AbundanceBySample) %>% ggplot(aes(x=Sample, y=RelAbundanceBySample, fill=label)) + geom_col() + facet_grid(.~subject, scales="free")
```

![xx5](https://user-images.githubusercontent.com/17870644/154474751-217ada23-9a09-410c-b11f-c4467b3171b2.PNG)

Or using other `geom` since the format has been converted to the tidy data format which is compatible with the ggplot2 or other extension package.

```
mpse %>% mp_cal_abundance(.abundance=Abundance, force=T) %>% mp_extract_abundance(taxa.class="Genus", topn="all", rmun=T) %>% dplyr::filter(label %in% c("g__Streptococcus", "g__Faecalibacterium")) %>% tidyr::unnest(AbundanceBySample) %>% ggplot(aes(x=body.site, y=RelAbundanceBySample, fill=body.site)) + geom_boxplot() +facet_grid(label~subject, scales="free_y")
```
![xx4](https://user-images.githubusercontent.com/17870644/154474400-6d8646ed-3f15-4d80-8303-5955b3553fd2.PNG)


PS : You can read about our [preprint](https://www.researchsquare.com/article/rs-1284357/v1) of `MicrobiotaProcess` if you want to know more about the `MicrobiotaProcess`.

**Comment by alienzj** [comment]
Thanks for the detailed explanation, very useful !
