### ISSUE TITLE
Under own folder，how to import data

### ISSUE THREAD

**Issue by YJL900223** [YuLab-SMU/MicrobiotaProcess#7]
mapfile <- system.file("extdata", "metadata_qza.txt", package="MicrobiotaProcess")

read.qza()??

**Comment by xiangpin** [comment]
Since you use R on windows, you can set the work path of R to your project, then use relative path to import. 
Example:`ps <- import_qiime2(otuqza="./feature.qza", taxaqza="./taxanomy.qza", mapfilename="./sample_group.txt")`.
Or you can use absolute path to import. Example:
`ps <- import_qiime2(otuqza="D:/Applications/R-devel/library/MicrobiotaProcess/extdata/table.qza", taxaqza="D:/Applications/R-devel/library/MicrobiotaProcess/extdata/taxa.qza", mapfilename="D:/Applications/R-devel/library/MicrobiotaProcess/extdata/metadata_qza.txt")`
I suggest you use relative path. If you don't konw how to set the work path of R to your project, please search by google or biying. Thanks!

**Comment by YJL900223** [comment]
Thank you very much!
