### ISSUE TITLE
set_diff_boxplot_color not found

### ISSUE THREAD

**Issue by olivierrue** [YuLab-SMU/MicrobiotaProcess#70]
Hi, 

I do not have access to set_diff_boxplot_color function.

```
f.box <- mpse %>%
         mp_plot_diff_boxplot(
           .group = Run,
         ) %>%
         set_diff_boxplot_color(
           values = c("deepskyblue", "orange"),
           guide = guide_legend(title=NULL)
         )
         
Erreur dans set_diff_boxplot_color(., values = c("deepskyblue", "orange"),  : 
  impossible de trouver la fonction "set_diff_boxplot_color"         

packageVersion('MicrobiotaProcess')
[1] ‘1.9.2.990’
 ```

Is the function missing in the latest release?
Thanks for your help

**Comment by xiangpin** [comment]
How about re-installing it using `remotes::install_github('YuLab-SMU/MicrobiotaProcess')`. Because `set_diff_boxplot_color` really exists in the [master branch of github](https://github.com/YuLab-SMU/MicrobiotaProcess/blob/43a5e9c695ef817424de50364ace9f8466608a1a/R/method-mp_diff_analysis.R#L1198-L1208). And it can work on my platform. I don't know why it didn't work on your platform.

**Comment by olivierrue** [comment]
Ok, it works after reinstallation !
Thanks
